
-- 表描述: 测试表
CREATE TABLE ABC (
  CD_NAME VARCHAR(20) NOT NULL,
  OLD_CD VARCHAR(20) NOT NULL,
  NEW_CD VARCHAR(20) NOT NULL,
  OP_DATE VARCHAR(8) NOT NULL,
  CD_DESC VARCHAR(30) NULL
) IN ABC_DATA_TBS INDEX IN ABC_IDX_TBS;

;

COMMENT ON TABLE ABC IS '测试表';
COMMENT ON COLUMN ABC.CD_NAME IS '代码名称';
COMMENT ON COLUMN ABC.OLD_CD IS '旧代码数值';
COMMENT ON COLUMN ABC.NEW_CD IS '新代码数值';
COMMENT ON COLUMN ABC.OP_DATE IS '登记日期';
COMMENT ON COLUMN ABC.CD_DESC IS '代码描述';

ALTER TABLE ABC ADD CONSTRAINT CBIS_CODE_SW_PK PRIMARY KEY  (CD_NAME, NEW_CD, OLD_CD);
CREATE INDEX CBIS_CODE_SW_IDX1 ON ABC (NEW_CD ASC, CD_NAME ASC);
CREATE INDEX CBIS_CODE_SW_IDX2 ON ABC (OLD_CD DESC, CD_NAME ASC);

-- 表描述: 测试表
CREATE TABLE ABC (
  CD_NAME VARCHAR(20) NOT NULL,
  OLD_CD VARCHAR(20) NOT NULL,
  NEW_CD VARCHAR(20) NOT NULL,
  OP_DATE VARCHAR(8) NOT NULL,
  CD_DESC VARCHAR(30) NULL
) IN ABC_DATA_TBS INDEX IN ABC_IDX_TBS;

;

COMMENT ON TABLE ABC IS '测试表';
COMMENT ON COLUMN ABC.CD_NAME IS '代码名称';
COMMENT ON COLUMN ABC.OLD_CD IS '旧代码数值';
COMMENT ON COLUMN ABC.NEW_CD IS '新代码数值';
COMMENT ON COLUMN ABC.OP_DATE IS '登记日期';
COMMENT ON COLUMN ABC.CD_DESC IS '代码描述';

ALTER TABLE ABC ADD CONSTRAINT CBIS_CODE_SW_PK PRIMARY KEY  (CD_NAME, NEW_CD, OLD_CD);
CREATE INDEX CBIS_CODE_SW_IDX1 ON ABC (NEW_CD ASC, CD_NAME ASC);
CREATE INDEX CBIS_CODE_SW_IDX2 ON ABC (OLD_CD DESC, CD_NAME ASC);

-- 表描述: 测试表
CREATE TABLE ABC (
  CD_NAME VARCHAR(20) NOT NULL,
  OLD_CD VARCHAR(20) NOT NULL,
  NEW_CD VARCHAR(20) NOT NULL,
  OP_DATE VARCHAR(8) NOT NULL,
  CD_DESC VARCHAR(30) NULL
) IN ABC_DATA_TBS INDEX IN ABC_IDX_TBS;

;

xxxxxxxxxxxxxxxxxxxxxCOMMENT ON TABLE ABC IS '测试表';
COMMENT ON COLUMN ABC.CD_NAME IS '代码名称';
COMMENT ON COLUMN ABC.OLD_CD IS '旧代码数值';
COMMENT ON COLUMN ABC.NEW_CD IS '新代码数值';
COMMENT ON COLUMN ABC.OP_DATE IS '登记日期';
COMMENT ON COLUMN ABC.CD_DESC IS '代码描述';

ALTER TABLE ABC ADD CONSTRAINT CBIS_CODE_SW_PK PRIMARY KEY  (CD_NAME, NEW_CD, OLD_CD);
CREATE INDEX CBIS_CODE_SW_IDX1 ON ABC (NEW_CD ASC, CD_NAME ASC);
CREATE INDEX CBIS_CODE_SW_IDX2 ON ABC (OLD_CD DESC, CD_NAME ASC);

-- 表描述: 测试表
CREATE TABLE ABC (
  CD_NAME VARCHAR(20) NOT NULL,
  OLD_CD VARCHAR(20) NOT NULL,
  NEW_CD VARCHAR(20) NOT NULL,
  OP_DATE VARCHAR(8) NOT NULL,
  CD_DESC VARCHAR(30) NULL
) IN ABC_DATA_TBS INDEX IN ABC_IDX_TBS;

COMMENT ON TABLE ABC IS '测试表';
COMMENT ON COLUMN ABC.CD_NAME IS '代码名称';
COMMENT ON COLUMN ABC.OLD_CD IS '旧代码数值';
COMMENT ON COLUMN ABC.NEW_CD IS '新代码数值';
COMMENT ON COLUMN ABC.OP_DATE IS '登记日期';
COMMENT ON COLUMN ABC.CD_DESC IS '代码描述';

ALTER TABLE ABC ADD CONSTRAINT CBIS_CODE_SW_PK PRIMARY KEY  (CD_NAME, NEW_CD, OLD_CD);
CREATE INDEX CBIS_CODE_SW_IDX1 ON ABC (NEW_CD ASC, CD_NAME ASC);
CREATE INDEX CBIS_CODE_SW_IDX2 ON ABC (OLD_CD DESC, CD_NAME ASC);
